name: Deploy to PRODUCTION

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: timeoff-manager-20251004
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # Wymaga manual approval w GitHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate version file
      run: |
        echo "{" > version.json
        echo "  \"commit\": \"$(git rev-parse --short HEAD)\"," >> version.json
        echo "  \"date\": \"$(date +%Y-%m-%d)\"," >> version.json
        echo "  \"branch\": \"${{ github.ref_name }}\"" >> version.json
        echo "}" >> version.json
        cat version.json

    - name: Run tests (if available)
      run: |
        echo "Running tests..."
        # pytest tests/ || true  # Uncomment when tests are added

    - name: Create deployment package
      run: |
        rm -rf venv
        zip -r deploy.zip . -x "*.git*" -x "*__pycache__*" -x "*.pyc" -x "venv/*" -x ".env" -x "terraform/*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip
        restart: true
        clean: true

    - name: Deployment notification
      if: success()
      run: |
        echo "✅ PRODUCTION Deployment successful!"
        echo "🔗 URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "🏷️  Tag: ${{ github.ref_name }}"

    - name: Deployment failed notification
      if: failure()
      run: |
        echo "❌ PRODUCTION Deployment failed - check logs above"
