name: Deploy to DEV

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: timeoff-manager-dev
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate version file
      run: |
        echo "{" > version.json
        echo "  \"commit\": \"$(git rev-parse --short HEAD)\"," >> version.json
        echo "  \"date\": \"$(date +%Y-%m-%d)\"," >> version.json
        echo "  \"branch\": \"${{ github.ref_name }}\"" >> version.json
        echo "}" >> version.json
        cat version.json

    - name: Run tests (if available)
      run: |
        echo "Running tests..."
        # pytest tests/ || true  # Uncomment when tests are added

    - name: Create deployment package
      run: |
        rm -rf venv
        zip -r deploy.zip . -x "*.git*" -x "*__pycache__*" -x "*.pyc" -x "venv/*" -x ".env" -x "terraform/*"

    - name: Deploy to Azure Web App (DEV)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
        package: deploy.zip

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Restart Azure Web App
      run: |
        az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group timeoff-manager-rg-dev
        echo "✅ App restarted to clear cache"

    - name: Deployment notification
      if: success()
      run: |
        echo "✅ DEV Deployment successful!"
        echo "🔗 URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"

    - name: Deployment failed notification
      if: failure()
      run: |
        echo "❌ DEV Deployment failed - check logs above"
